//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.

    HashMap<String, ClassRecord> classTable;
    Stack<String> scope;
    boolean build;
    MethodRecord currRecord;
    int labelNo;
    int tempNo;
    HashMap<String, Integer> tempMap;

    public GJDepthFirst() {
      classTable = new HashMap<String, ClassRecord>();
      scope = new Stack<String>();
      build = true;
      currRecord = null;
      labelNo = 0;
      tempNo = 0;
      tempMap = new HashMap<String, Integer>();
    }

    void addClass(String className, String parentName) {
      classTable.put(className, new ClassRecord(className, parentName));
    }

    public String getClassScope() {
      String currScope = scope.peek();
      if(currScope.charAt(currScope.length()-1) == ')')
         return scope.get(scope.size()-2);
      return currScope;
    }

    public String getMethodScope() {
      String currScope = scope.peek();
      if(currScope.charAt(currScope.length()-1) == ')')
         return currScope;
      return null;
    }

    int buildClass(String className) {
      int functionTableSize = classTable.get(className).methodCount;
      int objectSize = 4 + classTable.get(className).size();
      System.out.println("MOVE TEMP " + tempNo++ + " " + functionTableSize);
      System.out.println("MOVE TEMP " + tempNo + " HALLOCATE TEMP " + (tempNo-1));
      int functionTableLoc = tempNo;
      tempNo++;
      for(HashMap.Entry<String, Integer> entry: classTable.get(className).allMethods.entrySet()) {
         System.out.println("MOVE TEMP " + tempNo + " " + className + "_" + entry.getKey());
         System.out.println("HSTORE TEMP " + functionTableLoc + " " + entry.getValue() + " TEMP " + tempNo);
         tempNo++;
      }
      System.out.println("MOVE TEMP " + tempNo++ + " " + objectSize);
      System.out.println("MOVE TEMP " + tempNo + "HALLOCATE TEMP " + (tempNo-1));
      System.out.println("HSTORE TEMP " + tempNo + " 0 TEMP " + functionTableLoc);
      int objectLoc = tempNo;
      tempNo++;
      return objectLoc;
    }

    ArrayList<Integer> obtainVariable(String varName) {
      String className = getClassScope();
      ArrayList<Integer> ans = new ArrayList<Integer>();
      if(tempMap.containsKey(varName)) ans.add(tempMap.get(varName));
      else {
         int memberIndex = classTable.get(className).findMember(varName);
         if(memberIndex == -1) ans.add(-1);
         else {
            ans.add(0);
            ans.add(memberIndex);
         }
      }

      return ans;
    }

	 public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return (R)n.tokenImage; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> MainClass()
    * f1 -> ( TypeDeclaration() )*
    * f2 -> <EOF>
    */
   public R visit(Goal n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      for(HashMap.Entry<String, ClassRecord> entry: classTable.entrySet()) {
         entry.getValue().calculateSize();
         entry.getValue().countMethods();
      }

      // System.out.println("Build complete");

      // for(HashMap.Entry<String, ClassRecord> entry: classTable.entrySet())
      //    entry.getValue().printRecord(); 

      build = false;

      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);

      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      if(!build) System.out.println("MAIN");
      n.f0.accept(this, argu);
      String className = (String)n.f1.accept(this, argu);
      if(build) addClass(className, "");
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      if(!build) System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      String className = (String)n.f1.accept(this, argu);
      if(build) addClass(className, "");
      scope.push(className);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      scope.pop();
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      String className = (String)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String parentName = (String)n.f3.accept(this, argu);
      if(build) addClass(className, parentName);
      scope.push(className);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      scope.pop();
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String idType = (String)n.f0.accept(this, argu);
      String idName = (String)n.f1.accept(this, argu);
      if(build) {
         String classScope = getClassScope();
         String methodScope = getMethodScope();
         if(methodScope == null) classTable.get(classScope).addMember(idName, idType);
      }
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String className = getClassScope();
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String methodName = (String)n.f2.accept(this, argu);
      if(!build) {
         System.out.print(className + "_" + methodName + " [");
         ArrayList<String> params = classTable.get(className).getParams(methodName);
         tempNo = 1 + params.size();
         System.out.print(tempNo);
         System.out.println("]");
         System.out.println("BEGIN");
         tempMap = new HashMap<String, Integer>();
         tempMap.put("this", 0);
         for(int i = 0; i < params.size(); i++) tempMap.put(params.get(i), i+1);
      }
      if(build) currRecord = new MethodRecord(methodName);
      scope.push(methodName+"()");
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      int retExp = (int)n.f10.accept(this, argu);
      if(!build) System.out.println("RETURN TEMP " + retExp);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      if(build) classTable.get(className).addMethod(currRecord);
      scope.pop();
      if(!build) System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      String paramName = (String)n.f1.accept(this, argu);
      if(build) currRecord.addParam(paramName);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    */
   public R visit(Type n, A argu) {
		/* YOUR CODE HERE */

      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
		/* YOUR CODE HERE */

      R _ret=(R)"int[]";
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
		/* YOUR CODE HERE */

      R _ret=(R)"boolean";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
		/* YOUR CODE HERE */

      R _ret=(R)"int";
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String idName = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " TEMP " + exp);
         tempMap.put(idName, tempNo);
         tempNo++;
      }
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      String idName = (String)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int index = (int)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      int exp = (int)n.f5.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo++ + " PLUS TEMP " + tempMap.get(idName) + " TEMP " + index);
         System.out.println("MOVE TEMP " + tempNo++ + " 4");
         System.out.println("MOVE TEMP " + tempNo + " TIMES TEMP " + (tempNo-1) + " TEMP " + (tempNo-2));
         System.out.println("HSTORE TEMP " + tempNo + " 0 TEMP " + exp);
         tempNo++;
      }
      n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int currLabel = labelNo;
      labelNo++;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("CJUMP TEMP " + exp + " L" + currLabel);
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      if(!build) System.out.println("L" + currLabel);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int currLabel = labelNo;
      labelNo += 2;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("CJUMP TEMP " + exp + " L" + currLabel);
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      if(!build) {
         System.out.println("JUMP L" + (currLabel+1));
         System.out.println("L" + currLabel);
      }
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      System.out.println("L" + (currLabel+1));
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int currLabel = labelNo;
      labelNo += 2;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("L" + currLabel);
         System.out.println("CJUMP TEMP " + exp);
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      System.out.println("L" + (currLabel+1));
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp = (int)n.f2.accept(this, argu);
      if(!build) System.out.println("PRINT TEMP " + exp);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
		/* YOUR CODE HERE */

      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " AND TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " OR TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " LE TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " NE TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " PLUS TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " MINUS TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " TIMES TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp1 = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int exp2 = (int)n.f2.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " DIV TEMP " + exp1 + " TEMP " + exp2);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int index = (int)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo++ + " PLUS TEMP " + exp + " TEMP " + index);
         System.out.println("MOVE TEMP " + tempNo++ + " 4");
         System.out.println("MOVE TEMP " + tempNo + " TIMES TEMP " + (tempNo-1) + " TEMP " + (tempNo-2));
         tempNo++;
         System.out.println("HLOAD TEMP " + tempNo + " TEMP " + (tempNo-1) + " 0");
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp = (int)n.f0.accept(this, argu);
      if(!build) {
         System.out.println("HLOAD TEMP " + tempNo + " TEMP " + exp + " 0");
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int callObj = (int)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      if(!build) {
         // Identify the method
         int methodTemp = -1; //change
         System.out.print("MOVE TEMP " + tempNo++ + "CALL TEMP " + methodTemp + " ( ");
      }
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      if(!build) System.out.println(")");
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      int exp = (int)n.f0.accept(this, argu);
      if(!build) System.out.print("TEMP " + exp + " ");
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      int exp = (int)n.f1.accept(this, argu);
      if(!build) System.out.print("TEMP " + exp + " ");
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret = n.f0.accept(this, argu);
      if(!build) {
         ArrayList<Integer> idCheck = obtainVariable((String)_ret);
         if(idCheck.get(0) != -1) {
            // Do the appropriate
            // If size is 1, great! Just return it
            // What to do if greater than 1? i.e., it's part of the class
            if(idCheck.size() == 1) _ret = (R)((Integer)idCheck.get(0));
            else _ret = (R)((Integer)(-1 * idCheck.get(1)));
         }
      }
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
		/* YOUR CODE HERE */

      R _ret = null;
      int val = (int)n.f0.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " " + val);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
		/* YOUR CODE HERE */

      R _ret = null;
      n.f0.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " 1");
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
		/* YOUR CODE HERE */

      R _ret = null;
      n.f0.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " 0");
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
		/* YOUR CODE HERE */

      R _ret = n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      if(!build) _ret = (R)((Integer)0);
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      int exp = (int)n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo++ + " 1");
         System.out.println("MOVE TEMP " + tempNo + " PLUS TEMP " + exp + " TEMP " + (tempNo-1));
         tempNo++;
         System.out.println("MOVE TEMP " + tempNo++ + " 4");
         System.out.println("MOVE TEMP" + tempNo + " TIMES TEMP " + (tempNo-1) + " TEMP " + (tempNo-2));
         tempNo++;
         System.out.println("MOVE TEMP " + tempNo + "HALLOCATE " + (tempNo-1));
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      String className = (String)n.f1.accept(this, argu);
      if(!build) {
         _ret = (R)((Integer)buildClass(className));
      }
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      int exp = (int)n.f1.accept(this, argu);
      if(!build) {
         System.out.println("MOVE TEMP " + tempNo + " NOT TEMP " + exp);
         _ret = (R)((Integer)tempNo);
         tempNo++;
      }
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
		/* YOUR CODE HERE */

      R _ret=null;
      n.f0.accept(this, argu);
      R exp = n.f1.accept(this, argu);
      if(!build) _ret = exp;
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> ( IdentifierRest() )*
    */
   public R visit(IdentifierList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Identifier()
    */
   public R visit(IdentifierRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   class ClassRecord {
      String name, parentName;
      ArrayList<MethodRecord> functionTable;
      ArrayList<String> memberNames;
      ArrayList<String> memberTypes;
      int size, methodCount;
      boolean sizeCalculated;
      HashMap<String, Integer> allMethods;
      ArrayList<String> allMembers;
   
      ClassRecord(String name, String parent) {
         this.name = new String(name);
         this.parentName = new String(parent);
         functionTable = new ArrayList<MethodRecord>();
         memberNames = new ArrayList<String>();
         memberTypes = new ArrayList<String>();
         size = 0;
         methodCount = 0;
         sizeCalculated = false;
         allMethods = new HashMap<String, Integer>();
         allMembers = new ArrayList<String>();
      }
   
      void addMember(String memberName, String memberType) {
         memberNames.add(memberName);
         memberTypes.add(memberType);
      }
   
      void addMethod(MethodRecord method) {
         functionTable.add(method);
      }
   
      void calculateSize() {
         // Call after building to get size of record
         if(sizeCalculated) return;
         // size = memberNames.size();
         // if(!parentName.equals("")) {
         //    classTable.get(parentName).calculateSize();
         //    size += classTable.get(parentName).memberNames.size();
         // }
         // size *= 4;
         getAllMembers();
         size = 4 * allMembers.size();
         sizeCalculated = true;
      }
   
      void countMethods() {
         // Call after building to get total number of methods
         int count = 0;
         String className = name;
         while(!className.equals("")) {
            ClassRecord currClass = classTable.get(className);
            for(MethodRecord method: currClass.functionTable)
               if(!allMethods.containsKey(method.name)) {
                  allMethods.put(method.name, count);
                  count++;
               }

            className = currClass.parentName;
         }
         methodCount = count;
      }

      ArrayList<String> getParams(String methodName) {
         String className = name;
         while(!className.equals("")) {
            ClassRecord currClass = classTable.get(className);
            for(MethodRecord method: currClass.functionTable)
               if(methodName.equals(method.name)) return method.paramNames;
            className = currClass.parentName;
         }
         return null;
      }

      void getAllMembers() {
         allMembers = new ArrayList<String>(memberNames);
         if(!parentName.equals("")) {
            classTable.get(parentName).getAllMembers();
            ArrayList<String> parentMembers = classTable.get(parentName).allMembers;
            for(String member: parentMembers) allMembers.add(member);
         }
      }

      int findMember(String memberName) {
         for(int i = 0; i < allMembers.size(); i++) 
            if(memberName.equals(allMembers.get(i)))
               return i;
         return -1;
      }
      
      int size() { return size; }
   
      void printRecord() {
         System.out.println("Class " + name + " extends " + parentName);
         System.out.println("Size: " + size);
         System.out.println("Members:");
         for(int i = 0; i < memberNames.size(); i++)
            System.out.println(memberNames.get(i) + ": " + memberTypes.get(i));
         System.out.println("Methods: (count = " + methodCount + ")");
         for(MethodRecord method: functionTable) method.printRecord();
         System.out.println("\n");
      }
   }
   
   class MethodRecord {
      String name;
      ArrayList<String> paramNames;
   
      MethodRecord(String name) {
         this.name = new String(name);
         paramNames = new ArrayList<String>();
      }
   
      void addParam(String paramName) {
         paramNames.add(paramName);
      }
   
      void printRecord() {
         System.out.println(name);
         for(String param: paramNames) System.out.print(param + " ");
         System.out.println("");
      }
   }
   

}


